//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int ID { get; set; }
        public string MSSV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string GioiTinh { get; set; }
        public string NgaySinh { get; set; }
        public Nullable<int> ID_TinhTrang { get; set; }
        public Nullable<int> ID_Lop { get; set; }
        public string Email_1 { get; set; }
        public string Email_2 { get; set; }
        public string DTDD { get; set; }
        public string DTCha { get; set; }
        public string DTMe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> ID_Khoa { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
    
        public virtual KhoaDaoTao KhoaDaoTao { get; set; }
        public virtual LopQuanLy LopQuanLy { get; set; }
        public virtual NganhDaoTao NganhDaoTao { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
